### ISSUE TITLE
docker下面运行错误

### ISSUE THREAD

**Issue by liyiliuxingyu** [graviton1221/Danim#2]
root@fd05c35b59b1:/manim# python -m manim Danim/BubbleChart/BubbleChartAnimation.py BubbleChartAnimation -p
Media will be written to ./media/. You can change this behavior with the --media_dir flag.

Traceback (most recent call last):
  File "/manim/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/manim/manimlib/scene/scene.py", line 53, in __init__
    self.construct()
  File "Danim/BubbleChart/BubbleChartAnimation.py", line 6, in construct
    self.AllContriesComparison()
  File "Danim/BubbleChart/BubbleChartAnimation.py", line 15, in AllContriesComparison
    X,Y,R,entity_names,T = data_digest()
  File "/manim/Danim/BubbleChart/BCutils.py", line 46, in data_digest
    df = pd.read_csv(path,encoding = encoding ,index_col = 0)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'Danim\\DATA/X.csv' does not exist: b'Danim\\DATA/X.csv'

**Comment by graviton1221** [comment]
'Danim\DATA/X.csv' 看上去是识别的时候斜杠出了问题？可以查看下Danim\DATA下面是否有X.csv文件，然后可以查看下Danim/BubbleChart/bubble_constants.py中的DATA_DIR这个变量，它是控制输入数据的文件目录
